### ISSUE TITLE
Question to window farm

### ISSUE THREAD

**Issue by Jonisos** [waldobronchart/window-farm-client-rpi#2]
Hey!
Thanks for providing your code open source and publishing pictures for you window farm. I was wondering if you still remember which glass beaker you used? I was already searching for hours and simply couldn't find any beaker that's open at the top but has an outlet at the bottom.

Any help is appreciated! And sorry for using Github to ask this question. I thought maybe some people are wondering the same and could find it this way.

Thanks!

**Comment by waldobronchart** [comment]
Oh no I don't. I got them at a dollar store 😆 

The tricky thing is drilling a hole in the glass. I used a glass drillbit, but when you get through to the other side it's really easy to shatter the glass. 

I recommend using basic mason jars and drilling a hole directly in the middle bottom. You want to avoid having water not completely draining away.

Good luck!

**Comment by Jonisos** [comment]
Awesome, thank you for answering! I already ordered glass drills upon inspecting the far away picture of your window farm a thousand times. The barely visible glas imprint on the front of your jars reminded me of "Weck" mason jars and lead me that way.

Many thanks for the tips on drilling. I was thinking about drilling on the side to make it look nicer but now I will stick to the bottom which is probably easier to drill anyway.
